server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingmicro
    username: root
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

okta:
  oauth2:
    issuer: https://dev-22186400.okta.com/oauth2/default
    audience: api://default




#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultzone: http://localhost:8761/eureka